# Generated by Django 5.2.5 on 2025-08-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_author_language_alter_book_title_of_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='language',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.CharField(max_length=5),
        ),
    ]
